# curl --location 'localhost:8080/api/v1/create-contact'
#--header 'Content-Type: application/json'
#--data '{
#    "name": "Alonusz",
#    "lastName": "Ohansus",
#    "phone_number": "5554-77"
#}'
POST localhost:8080/api/v1/create-contact
Content-Type: application/json

{
  "name": "Alonusz",
  "lastName": "Ohansus",
  "phone_number": "052-840-8722"
}

###

# curl --location 'localhost:8080/api/v1/create-contact'
#--header 'Content-Type: application/json'
#--data '{
#    "name": "Alonusz",
#    "lastName": "Ohansus",
#    "phone_number": "5554-77"
#}'
POST localhost:8080/api/v1/create-contact
Content-Type: application/json

{
  "name": "Eliahu",
  "lastName": "Anavim",
  "phone_number": "053-844-8722"
}

###

# curl --location 'localhost:8080/api/v1/read-contacts'
GET localhost:8080/api/v1/read-contacts

###
# curl --location --request PATCH 'localhost:8080/api/v1/update-contact-by-name'
#--header 'Content-Type: application/json'
#--data '{
#    "phone_number": "123-456-7893",
#    "name": "Alon",
#    "lastName": "Ohana"
#}'
PATCH localhost:8080/api/v1/update-contact-by-name
Content-Type: application/json

{
  "name": "Alonusz",
  "lastName": "Ohansus",
  "phone_number": "052-840-8723"
}

###

# curl --location --request PATCH 'localhost:8080/api/v1/update-contact-by-phone'
#--header 'Content-Type: application/json'
#--data '{
#    "phone_number": "052-840-8722",
#    "name": "Alon",
#    "lastName": "Ohana"
#}'
PATCH localhost:8080/api/v1/update-contact-by-phone
Content-Type: application/json

{
  "name": "Alon",
  "lastName": "Ohana",
  "phone_number": "052-840-8723"
}

###

# curl --location 'localhost:8080/api/v1/read-contacts'
GET localhost:8080/api/v1/read-contacts

###

# curl --location --request DELETE 'localhost:8080/api/v1/delete-contact'
#--header 'Content-Type: application/json'
#--data '{
#    "phone_number":"052-840-8722"
#}'
DELETE localhost:8080/api/v1/delete-contact
Content-Type: application/json

{
  "phone_number": "052-840-8723"
}

###

# curl --location 'localhost:8080/api/v1/search-contacts'
#--header 'Content-Type: application/json'
#--data '{
#    "phone_number": "123-"
#}'
POST localhost:8080/api/v1/search-contacts
Content-Type: application/json

{
  "phone_number": "053-"
}

###

